name: Deploy Function App on Linux environment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]
    
env:
  AZURE_FUNCTIONAPP_NAME: fapp-personal-dev-linux  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'              # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                          # set this to the dotnet version to use
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3
      
    - name: Setup .NET ${{ env.DOTNET_VERSION }} SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    
    - name: 'Azure CLI Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
          
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1.4.6
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear

    
